%% run_BB_analysis.m
% Driver script for the WSN Black Box analysis

clear;
clc;
close all;

%% Simulation parameters
numSensors = 50;
communicationRadius = 0.3;
numEvents = 100;

%% Run the WSN simulation
[sensorsPos, communicationCount, receivedEventCount, ...
    averageDelay, delays] = ...
    WSN_BB1_SysML(numSensors, communicationRadius, numEvents);

%% Display simulation results
fprintf('Average communication delay: %.4f\n', averageDelay);
fprintf('Total communications: %d\n', sum(communicationCount));
fprintf('Total events received: %d\n', sum(receivedEventCount));

%% Plot sensor positions
data_visualization(sensorsPos, "scatter", ...
    "X Position", ...
    "Y Position", ...
    "Sensor Positions");

%% Plot communication count
data_visualization(communicationCount, "bar", ...
    "Sensor", ...
    "Number of Communications", ...
    "Communications per Sensor");

%% Plot received events
data_visualization(receivedEventCount, "bar", ...
    "Sensor", ...
    "Events Received", ...
    "Events Received per Sensor");

%% Plot communication delays
data_visualization(delays, "hist", ...
    "Delay", ...
    "Frequency", ...
    "Communication Delay Distribution");